### ISSUE TITLE
Bash fails on `stage1:05-and-or-chaining.t` due to error message

### ISSUE THREAD

**Issue by fredrb** [tokenrove/build-your-own-shell#10]
I tried running the tests with both `bash` and `zsh` and they both fail on the same test (`05-and-or-chaining.t`)

```
❯ ./validate /usr/bin/bash
stage_1: 01-fork-exec.t 02-commands-invoked-from-path.t 03-cd-changes-directory.t 04-semicolon-separates-commands.t 05-and-or-chaining.t

# POSIX calls these AND Lists and OR Lists
→ true && echo-rot13 foo⏎
← sbb
→ false && echo-rot13 foo⏎
≠ sbb
→ true && false && echo-rot13 foo⏎
≠ sbb
→ false || echo-rot13 foo⏎
← sbb
→ true || false || echo-rot13 foo⏎
≠ sbb
→ false || true && echo-rot13 foo⏎
← sbb
→ nonexistent-command 2>/dev/null || echo-rot13 zim⏎
← mvz

---------------------------
You still need to do stage_1
Keep working!
```

Seems like they are failing on the last assertion of the test case:
```
→ nonexistent-command || echo-rot13 zim⏎
← mvz
```

I ran the tests in interactive mode and I believe the problem is that both `bash` and `zsh` are printing an error message for the command not found. Here's an example in a vanilla bash shell:

```
$ nonexistent-command || ./helpers/echo-rot13 zim
bash: nonexistent-command: command not found...
mvz
```

## Versions
```
❯ expect -v
expect version 5.45.4
```

```
❯ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu)
```

```
❯ zsh --version
zsh 5.9 (x86_64-redhat-linux-gnu)
```

**Comment by tokenrove** [comment]
Thanks for bringing this up!  I actually have some long-languishing changes for this repo that fix a bunch of issues, so knowing someone is looking at it is perhaps a little kick to do that.

With regards this issue, this is interesting, because `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)` passes the tests for me, on Debian.  That message should be printed on stderr, and the harness (as I recall) only cares about stdout.  What distribution are you using (clearly something Redhat-derived)?

I have been planning to work on the robustness of the harness for ages, since it behaves badly on macOS, at least when I checked some years ago.

**Comment by tokenrove** [comment]
So, I reproduced this on Fedora, and surprisingly, increasing the sleep after sending a line to 0.5 seconds causes it to pass.  It surprises me that we'd see this difference between two distributions; maybe PS1 is more expensive on Fedora or something?  Seems unlikely.  I'll look into it as part of trying to make this more reliable on a variety of systems.

**Comment by tokenrove** [comment]
Oh, it's because Fedora's profile includes code that sets `command_not_found_handle` to some things that take more than 0.2 seconds on every non-existent command.  I'll just try to make it less sensitive to timing.

**Comment by fredrb** [comment]
Thanks for looking this up! And yea, I'm running on Fedora
